name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    concurrency:
      group: bot-run
      cancel-in-progress: false

    env:
      LICHESS_KEY: ${{ secrets.LICHESS_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies & prepare
        run: |
          pip install --no-cache-dir --prefer-binary -r requirements.txt
          sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml
          chmod +x ./engines/stockfish-ubuntu-x86-64-bmi2 ./engines/fairy-stockfish_x86-64-bmi2 ./engines/stockfish-7-x64-bmi2

      - name: Verify environment variables
        run: |
          echo "LICHESS_KEY: $LICHESS_KEY"
          echo "BOT_TOKEN: $BOT_TOKEN"
          echo "PYTHONPATH: $PYTHONPATH"
          echo "Current directory: $(pwd)"
          ls -la
          ls -la ./engines
          ls -la ./config.yml
          ls -la ./user_interface.py

      - name: Check Python version
        run: |
          python3 --version
          pip3 --version

      - name: Run Bot with Detailed Logging
        run: |
          echo "Starting bot..."
          export LICHESS_KEY=${{ secrets.LICHESS_KEY }}
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          
          # Запуск бота с подробным логированием
          python3 -u user_interface.py "matchmaking" "tournament JUT6xRg3" >> bot.log 2>&1
          
          # Проверка статуса выполнения
          if [ $? -ne 0 ]; then
            echo "Bot failed to start"
            cat bot.log
            exit 1
          fi

      - name: Verify bot.log contents
        if: failure()
        run: |
          echo "Contents of bot.log:"
          cat bot.log

      - name: 🔁 Self-Restart
        if: always()
        run: gh workflow run "Run bot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
