name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git credentials
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token=${GITHUB_TOKEN}@github.com/Sozdatel1/is_BOSS-DEPLOY.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ github.token }}
