name: Download and Commit Stockfish

on:
  workflow_dispatch:

jobs:
  download_and_commit_stockfish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0   # fetch full history to allow rebasing

      - name: Download latest Stockfish
        run: |
          curl -L "https://github.com/official-stockfish/Stockfish/releases/download/stockfish-dev-20251014-75edbee0/stockfish-ubuntu-x86-64-bmi2.tar" -o stockfish.tar
          tar -xf stockfish.tar

      - name: Move Stockfish binary to engines folder (keep original name)
        run: |
          mkdir -p engines
          mv stockfish/stockfish-ubuntu-x86-64-bmi2 engines/
          chmod +x engines/stockfish-ubuntu-x86-64-bmi2

      - name: Clean up
        run: rm -rf stockfish stockfish.tar

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add engines/stockfish-ubuntu-x86-64-bmi2
          git commit -m "Update Stockfish binary" || echo "No changes to commit"
          git pull --rebase origin main
          git push
